title: "Frey"
subtitle: "Frey is an end-to-end sysadmin toolbelt for developers."
description: "Frey describes your app's infra & prerequisites in a single file, and let's you deploy all of it, in a single command. "
gems:
  - jekyll-redirect-from
