decaffeinate ./src/Base.coffee && rm -f ./src/Base.coffee
decaffeinate ./src/Command.coffee && rm -f ./src/Command.coffee
decaffeinate ./src/commands/Backup.coffee && rm -f ./src/commands/Backup.coffee
decaffeinate ./src/commands/Deploy.coffee && rm -f ./src/commands/Deploy.coffee
decaffeinate ./src/commands/Docbuild.coffee && rm -f ./src/commands/Docbuild.coffee
decaffeinate ./src/commands/Install.coffee && rm -f ./src/commands/Install.coffee
decaffeinate ./src/commands/Launch.coffee && rm -f ./src/commands/Launch.coffee
decaffeinate ./src/commands/Plan.coffee && rm -f ./src/commands/Plan.coffee
decaffeinate ./src/commands/Prepare.coffee && rm -f ./src/commands/Prepare.coffee
decaffeinate ./src/commands/Refresh.coffee && rm -f ./src/commands/Refresh.coffee
decaffeinate ./src/commands/Remote.coffee && rm -f ./src/commands/Remote.coffee
decaffeinate ./src/commands/Restart.coffee && rm -f ./src/commands/Restart.coffee
decaffeinate ./src/commands/Restore.coffee && rm -f ./src/commands/Restore.coffee
decaffeinate ./src/commands/Runtime.coffee && rm -f ./src/commands/Runtime.coffee
decaffeinate ./src/commands/Show.coffee && rm -f ./src/commands/Show.coffee
decaffeinate ./src/commands/Validate.coffee && rm -f ./src/commands/Validate.coffee
decaffeinate ./src/Frey.coffee && rm -f ./src/Frey.coffee
decaffeinate ./test/test-Base.coffee && rm -f ./test/test-Base.coffee
decaffeinate ./test/test-Command.coffee && rm -f ./test/test-Command.coffee
decaffeinate ./test/test-Frey.coffee && rm -f ./test/test-Frey.coffee
